# For debugging use:
# hugo config --format yaml | less

title: Dmitry Konishchev's small blog
baseURL: https://konishchev.ru/

# FIXME(konishchev): Enable?
# copyright: "© [Dmitry Konishchev](mailto:konishchev@gmail.com)"

languageCode: ru
defaultContentLanguage: ru

# We don't use tags and categories, so don't generate them
disableKinds: ["taxonomy"]

theme: papermodx
# FIXME(konishchev): Change style after theme tunning
markup:
  highlight:
    style: vs

enableGitInfo: true
cleanDestinationDir: true