defaultTheme: light
disableThemeToggle: true

disableSpecial1stPost: true
dateFormat: 2 January 2006
showCodeCopyButtons: true
showFullTextInRSS: true

showToc: true
tocOpen: true
tocSide: right

socialIcons:
  - name: Email
    url: mailto:konishchev@gmail.com

  - name: GitHub
    url: https://github.com/KonishchevDmitry

  - name: LinkedIn
    url: https://www.linkedin.com/in/konishchev/

  - name: RSS
    url: /rss.xml